class 'ClothingsList'

function ClothingsList:__init()

	self["SKIN"] = {
		["1"] = {value = 1000, name = "pd_thugs1"},
		["2"] = {value = 1000, name = "mc09_razman"},
		["3"] = {value = 1000, name = "pd_ms_gov_demoexpert"},
		["4"] = {value = 1000, name = "pd_tourist_female1"},
		["5"] = {value = 1000, name = "pd_roacheselite1"},
		["6"] = {value = 1000, name = "pd_ms_bodyguardchinese"},
		["7"] = {value = 1000, name = "pd_city_male_1"},
		["8"] = {value = 1000, name = "pd_ms_reapers_technician"},
		["9"] = {value = 1000, name = "mc04_karlblaine"},
		["10"] = {value = 1000, name = "pd_generic_male_1"},
		["11"] = {value = 1000, name = "mc14_zhangsun"},
		["12"] = {value = 1000, name = "pd_reapersbase1"},
		["13"] = {value = 1000, name = "pd_generic_male_3"},
		["14"] = {value = 1000, name = "pd_generic_female_4"},
		["15"] = {value = 1000, name = "pd_ms_strippers_male1"},
		["16"] = {value = 1000, name = "pd_panaupolice"},
		["17"] = {value = 1000, name = "pd_ms_strippers_male2"},
		["18"] = {value = 1000, name = "pd_ms_hacker"},
		["19"] = {value = 1000, name = "pd_ms_chinabusinessman"},
		["20"] = {value = 1000, name = "invisibledoll"},
		["21"] = {value = 1000, name = "pd_ms_paparazzi"},
		["22"] = {value = 1000, name = "pd_ms_ular_technician"},
		["23"] = {value = 1000, name = "pd_ms_scientist_male"},
		["24"] = {value = 1000, name = "pd_generic_male_4"},
		["25"] = {value = 1000, name = "mc11_kane"},
		["26"] = {value = 1000, name = "pd_ms_boatcaptain"},
		["27"] = {value = 1000, name = "pd_ularboysbase1"},
		["28"] = {value = 1000, name = "pd_generic_male_2"},
		["29"] = {value = 1000, name = "pd_fishervillage_male2"},
		["30"] = {value = 1000, name = "pd_ms_strandedcopilot"},
		["31"] = {value = 1000, name = "pd_arcticvillage_female3"},
		["32"] = {value = 1000, name = "pd_ms_roaches_technician"},
		["33"] = {value = 1000, name = "pd_ms_gambler"},
		["34"] = {value = 1000, name = "mc12_sheldon"},
		["35"] = {value = 1000, name = "pd_city_male_2"},
		["36"] = {value = 1000, name = "pd_ms_politician"},
		["37"] = {value = 1000, name = "pd_generic_religious_male"},
		["38"] = {value = 1000, name = "mc06_sicini"},
		["39"] = {value = 1000, name = "pd_thugs2"},
		["40"] = {value = 1000, name = "pd_ms_factoryboss"},
		["41"] = {value = 1000, name = "pd_arcticvillage_female1"},
		["42"] = {value = 1000, name = "pd_blackhand"},
		["43"] = {value = 1000, name = "pd_ms_civ_strippers_male1"},
		["44"] = {value = 1000, name = "pd_ninja"},
		["45"] = {value = 1000, name = "pd_ms_waiter"},
		["46"] = {value = 1000, name = "pd_generic_female_1"},
		["47"] = {value = 1000, name = "pd_generic_female_2"},
		["48"] = {value = 1000, name = "pd_ms_doorman"},
		["49"] = {value = 1000, name = "pd_ms_govcaptain"},
		["50"] = {value = 1000, name = "pd_oilplatform_male2"},
		["51"] = {value = 1000, name = "mc01_rico"},
		["52"] = {value = 1000, name = "pd_gov_base02"},
		["53"] = {value = 1000, name = "pd_ms_civ_strippers_female1"},
		["54"] = {value = 1000, name = "pd_ms_bodyguardrussian"},
		["55"] = {value = 1000, name = "pd_ms_exclusiveguest_variant1"},
		["56"] = {value = 1000, name = "pd_fishervillage_male1"},
		["57"] = {value = 1000, name = "pd_oilplatform_male1"},
		["58"] = {value = 1000, name = "pd_reapersbase2"},
		["59"] = {value = 1000, name = "pd_roachesbase2"},
		["60"] = {value = 1000, name = "pd_ms_racechallengegirl"},
		["61"] = {value = 1000, name = "pd_factioninterest_general"},
		["62"] = {value = 1000, name = "pd_desertvillage_female1"},
		["63"] = {value = 1000, name = "pd_reaperselite1"},
		["64"] = {value = 1000, name = "pd_ms_bombombohilano"},
		["65"] = {value = 1000, name = "mc02_jadetan"},
		["66"] = {value = 1000, name = "pd_gov_base01"},
		["67"] = {value = 1000, name = "mc05_burned_rocketbaby"},
		["68"] = {value = 1000, name = "pd_fishervillage_male4"},
		["69"] = {value = 1000, name = "pd_ms_witness"},
		["70"] = {value = 1000, name = "mc03_generalmasayo"},
		["71"] = {value = 1000, name = "pd_ms_saulsukarno"},
		["72"] = {value = 1000, name = "pd_generic_female_5"},
		["73"] = {value = 1000, name = "pd_arcticvillage_male3"},
		["74"] = {value = 1000, name = "mc05_babypanay"},
		["75"] = {value = 1000, name = "pd_arcticvillage_male1"},
		["76"] = {value = 1000, name = "pd_generic_male_5"},
		["77"] = {value = 1000, name = "pd_gov_elite"},
		["78"] = {value = 1000, name = "pd_ms_thugboss"},
		["79"] = {value = 1000, name = "pd_ms_japaneseveterans"},
		["80"] = {value = 1000, name = "pd_ms_exclusiveguest"},
		["81"] = {value = 1000, name = "pd_ms_civ_strippers_male2"},
		["82"] = {value = 1000, name = "pd_tourist_female2"},
		["83"] = {value = 1000, name = "pd_ms_whitetigers"},
		["84"] = {value = 1000, name = "mc13_alexandermirikov"},
		["85"] = {value = 1000, name = "pd_roachesbase1"},
		["86"] = {value = 1000, name = "pd_ms_strippers_female1"},
		["87"] = {value = 1000, name = "pd_ularboyselite1"},
		["88"] = {value = 1000, name = "pd_tourist_male1"},
		["89"] = {value = 1000, name = "pd_ms_factoryworkers"},
		["90"] = {value = 1000, name = "mc10_santosi"},
		["91"] = {value = 1000, name = "pd_arcticvillage_male2"},
		["92"] = {value = 1000, name = "pd_city_female_1"},
		["93"] = {value = 1000, name = "pd_fishervillage_male3"},
		["94"] = {value = 1000, name = "pd_generic_female_3"},
		["95"] = {value = 1000, name = "pd_ms_exclusiveguest_variant2"},
		["96"] = {value = 1000, name = "pd_ms_bodyguardjapanese"},
		["97"] = {value = 1000, name = "mc05_burned_babypanay"},
		["98"] = {value = 1000, name = "pd_ms_gov_pilot"},
		["99"] = {value = 1000, name = "pd_desertvillage_male1"},
		["100"] = {value = 1000, name = "pd_blackmarket"},
		["101"] = {value = 1000, name = "pd_ms_gov_shielder"},
		["102"] = {value = 1000, name = "pd_arcticvillage_female2"},
		["103"] = {value = 1000, name = "pd_ularboysbase2"},
	}
	
	self["HAT"] = {
		["pd_arcticvillage_female1.eez/pd_arcticvillage_female-headcloth.lod"] = {value = 1000, name = "Chapeu de Pano do Ártico"},
		["pd_arcticvillage_female1.eez/pd_arcticvillage_female-headcloth2.lod"] = {value = 1000, name = "Chapeu de Pano do Ártico 2s"},
		["pd_arcticvillage_female2.eez/pd_arcticvillage_female_2-hat_winter.lod"] = {value = 1000, name = "Chapeu de Inverno do Ártico"},
		["pd_arcticvillage_male1.eez/pd_arcticvillage_male-hat.lod"] = {value = 1000, name = "Chapeu do Ártico"},
		["pd_arcticvillage_male2.eez/pd_arcticvillage_male_2-hat_winter.lod"] = {value = 1000, name = "Chapeu de Inverno"},
		["pd_blackmarket.eez/pd_blackmarket-scarf.lod"] = {value = 1000, name = "Cachecol"},
		["pd_desertvillage_female1.eez/pd_desertvillage_female_shawl.lod"] = {value = 1000, name = "Xale do Deserto"},
		["pd_desertvillage_male1.eez/pd_desertvillage_male-turban.lod"] = {value = 1000, name = "Turbante do Deserto"},
		["pd_fishervillage_male1.eez/pd_fishervillage_male-hat_fisherman.lod"] = {value = 1000, name = "Chapeu do Pescador"},
		["pd_fishervillage_male1.eez/pd_fishervillage_male-ricehat.lod"] = {value = 1000, name = "Chapeu de Arroz"},
		["pd_generic_female.eez/generic_female-ricehat.lod"] = {value = 1000, name = "Chapeu de Arroz 2"},
		["pd_generic_female.eez/generic_female-shawl.lod"] = {value = 1000, name = "Xale"},
		["pd_generic_female_1.eez/pd_generic_female_1-hat_fisherman.lod"] = {value = 1000, name = "Chapeu do Pescador"},
		["pd_generic_female_1.eez/pd_generic_female_1-hat_linen.lod"] = {value = 1000, name = "Chapeu de Linho"},
		["pd_generic_female_1.eez/pd_generic_female_1-hat_rice.lod"] = {value = 1000, name = "Chapeu de Arroz 3"},
		["pd_generic_female_2.eez/pd_generic_female_2-hat_linen.lod"] = {value = 1000, name = "Chapeu de Linho 2"},
		["pd_generic_female_2.eez/pd_generic_female_2-hat_rice.lod"] = {value = 1000, name = "Chapeu de Arroz 4"},
		["pd_generic_female_2.eez/pd_generic_female_2-hat_towel.lod"] = {value = 1000, name = "Chapeu de Toalha"},
		["pd_generic_female_3.eez/pd_generic_female_3-hat_towel.lod"] = {value = 1000, name = "Chapeu de Toalha 2"},
		["pd_generic_female_3.eez/pd_generic_female_3-hat_straw2.lod"] = {value = 1000, name = "Chapeu de Palha"},
		["pd_generic_female_3.eez/pd_generic_female_3-hat_scarf.lod"] = {value = 1000, name = "Chapeu com Cachecol"},
		["pd_generic_female_5.eez/pd_generic_female_5-hat_cloth.lod"] = {value = 1000, name = "Chapeu de Pano"},
		["pd_generic_female_5.eez/pd_generic_female_5-hat_scarf.lod"] = {value = 1000, name = "Chapeu de Cachecol 2"},
		["pd_generic_female_5.eez/pd_generic_female_5-hat_straw2.lod"] = {value = 1000, name = "Chapeu com Cachecol 3"},
		["pd_generic_male.eez/pd_generic_male-hat.lod"] = {value = 1000, name = "Chapeu"},
		["pd_generic_male_1.eez/pd_generic_male_1-hat_fisherman.lod"] = {value = 1000, name = "Chapeu do Pescador"},
		["pd_generic_male_1.eez/pd_generic_male_1-hat_linen.lod"] = {value = 1000, name = "Chapeu"},
		["pd_generic_male_1.eez/pd_generic_male_1-hat_rice.lod"] = {value = 1000, name = "Chapeu"},
		["pd_generic_male_2.eez/pd_generic_male_2-hat_fedora.lod"] = {value = 1000, name = "Chapeu"},
		["pd_generic_male_2.eez/pd_generic_male_2-hat_linen.lod"] = {value = 1000, name = "Chapeu"},
		["pd_generic_male_2.eez/pd_generic_male_2-hat_weird.lod"] = {value = 1000, name = "Chapeu"},
		["pd_generic_male_3.eez/pd_generic_male_3-hat_linen.lod"] = {value = 1000, name = "Chapeu"},
		["pd_gov_base01.eez/pd_gov_base-beret.lod"] = {value = 1000, name = "Chapeu"},
		["pd_gov_base01.eez/pd_gov_base-hat.lod"] = {value = 1000, name = "Chapeu"},
		["pd_gov_base01.eez/pd_gov_base-hat.lod"] = {value = 1000, name = "Chapeu"},
		["pd_gov_elite.eez/pd_govnewfix_elite-beret2.lod"] = {value = 1000, name = "Chapeu"},
		["pd_gov_elite.eez/pd_govnewfix_elite-helmet.lod"] = {value = 1000, name = "Chapeu"},
		["pd_ms_airport_female1.eez/pd_ms_airport_female-cap.lod"] = {value = 1000, name = "Chapeu"},
		["pd_ms_airport_male1.eez/pd_ms_airport_male-cap.lod"] = {value = 1000, name = "Chapeu"},
		["pd_ms_civ_strippers_female1.eez/pd_civilian_stripper_female-ht_millitarycap.lod"] = {value = 1000, name = "Chapeu"},
		["pd_ms_civ_strippers_male1.eez/pd_civilian_stripper_male-hat.lod"] = {value = 1000, name = "Chapeu"},
		["pd_ms_civ_strippers_male2.eez/pd_civilian_stripper_male-cowboyhat.lod"] = {value = 1000, name = "Chapeu"},
		["pd_ms_civ_strippers_male2.eez/pd_civilian_stripper_male-cowboyscarf.lod"] = {value = 1000, name = "Chapeu"},
		["pd_ms_doorman.eez/pd_doorman-h_bandana.lod"] = {value = 1000, name = "Chapeu"},
		["pd_ms_japaneseveterans.eez/pd_ms_japaneseveterans-hat.lod"] = {value = 1000, name = "Chapeu"},
		["pd_ms_japaneseveterans.eez/pd_ms_japaneseveterans-helmet.lod"] = {value = 1000, name = "Chapeu"},
		["pd_ms_strippers_female1.eez/pd_stripper_female-ht_millitarycap.lod"] = {value = 1000, name = "Chapeu"},
		["pd_ms_strippers_male1.eez/pd_stripper_male-hat.lod"] = {value = 1000, name = "Chapeu"},
		["pd_ms_strippers_male2.eez/pd_ms_stripper_male-cowboyhat.lod"] = {value = 1000, name = "Chapeu"},
		["pd_ms_strippers_male2.eez/pd_ms_stripper_male-cowboyscarf.lod"] = {value = 1000, name = "Chapeu"},
		["pd_ms_thugboss.eez/pd_executioner-h_felthat.lod"] = {value = 1000, name = "Chapeu"},
		["pd_oilplatform_male1.eez/pd_oilplatform-greycap.lod"] = {value = 1000, name = "Chapeu"},
		["pd_oilplatform_male1.eez/pd_oilplatform-helmet.lod"] = {value = 1000, name = "Chapeu"},
		["pd_panaupolice.eez/panaupolice-helmet.lod"] = {value = 1000, name = "Chapeu"},
		["pd_panaupolice.eez/panaupolice-turban.lod"] = {value = 1000, name = "Chapeu"},
		["pd_panaupolice.eez/panaupolice-cap.lod"] = {value = 1000, name = "Chapeu"},
		["pd_reaperselite1.eez/pd_reapers_elite_male-beret.lod"] = {value = 1000, name = "Chapeu"},
		["pd_reaperselite1.eez/pd_reapers_elite_male-cap.lod"] = {value = 1000, name = "Chapeu"},
		["pd_roacheselite1.eez/pd_roaches_elite-h_bandana.lod"] = {value = 1000, name = "Chapeu"},
		["pd_roacheselite1.eez/pd_roaches_elite-h_headwear.lod"] = {value = 1000, name = "Chapeu"},
		["pd_thugs1.eez/pd_thugs-h_bandana.lod"] = {value = 1000, name = "Chapeu"},
		["pd_thugs1.eez/pd_thugs-h_felthat.lod"] = {value = 1000, name = "Chapeu"},
		["pd_tourist_female2.eez/pd_tourist_female-h_fisherhat.lod"] = {value = 1000, name = "Chapeu"},
		["pd_tourist_female2.eez/pd_tourist_female-h_keps.lod"] = {value = 1000, name = "Chapeu"},
		["pd_tourist_male1.eez/pd_tourist_male-fisherhat.lod"] = {value = 1000, name = "Chapeu"},
		["pd_tourist_male1.eez/pd_tourist_male-keps.lod"] = {value = 1000, name = "Chapeu"},

	}
	
	self["GLASSES"] = {
		["pd_blackhand.eez/pd_blackhand-glasses.lod"] = {value = 1000, name = "Oculos"},
		["pd_ms_civ_strippers_female1.eez/pd_civilian_stripper_female-a_sunglasses.lod"] = {value = 1000, name = "Oculos"},
		["pd_ms_civ_strippers_male1.eez/pd_civilian_stripper_male-sunglasses.lod"] = {value = 1000, name = "Oculos"},
		["pd_ms_scientist_male.eez/pd_ms_scientist_glasses.lod"] = {value = 1000, name = "Oculos"},
		["pd_ms_strippers_female1.eez/pd_stripper_Female-a_sunglasses.lod"] = {value = 1000, name = "Oculos"},
		["pd_ms_strippers_male1.eez/pd_stripper_male-sunglasses.lod"] = {value = 1000, name = "Oculos"},
		["pd_thugs1.eez/pd_thugs-o-glasses.lod"] = {value = 1000, name = "Oculos"},
		["pd_tourist_female2.eez/pd_tourist_female-h_sunglasses.lod"] = {value = 1000, name = "Oculos"},
		["pd_tourist_male1.eez/pd_tourist_male-sunglasses.lod"] = {value = 1000, name = "Oculos"},
		["pd_ularboyselite1.eez/pd_ularboys_elite_male-glasses.lod"] = {value = 1000, name = "Oculos"},
	}
	
	self["BAG"] = {
		["pd_gov_base02.eez/pd_gov_base-bags.lod"] = {value = 1000, name = "Bag"},
		["pd_gov_elite.eez/pd_govnewfix_elite-vest1.lod"] = {value = 1000, name = "Bag"},
		["pd_gov_elite.eez/pd_govnewfix_elite-vest2qw.lod"] = {value = 1000, name = "Bag"},
		["pd_ularboysbase1.eez/pd_ularboys_base_male-backpack.lod"] = {value = 1000, name = "Bag"},
		
	}
	
	self["TIE"] = {
		["pd_ms_airport_female2.eez/pd_ms_airport_female-tie.lod"] = {value = 1000, name = "Gravata"},
		["pd_ms_airport_male1.eez/pd_ms_airport_male-tie.lod"] = {value = 1000, name = "Gravata"},
		["pd_city_male1.eez/pd_city_male_1-costume.lod"] = {value = 1000, name = "Gravata"},
		
	}
	
	self["BELT"] = {
		["pd_Reapersbase1.eez/pd_reapers_base_male-waisbelt.lod"] = {value = 1000, name = "BELT"},
		["pd_Reapersbase1.eez/pd_reapers_base_male-waisbeltb.lod"] = {value = 1000, name = "BELT"},
		
	}
end