class 'ListaVestimentas'

function ListaVestimentas:__init()

	self.vestimentas = {
		[1] = {
			nome = "Roupas",
			[1] = {nome = "Thug1", preco = 30000},
			[2] = {nome = "Razak Razman", preco = 3000},
			[3] = {nome = "Demo Expert", preco = 3000},
			[5] = {nome = "Roaches Elite", preco = 3000},
			[6] = {nome = "Chinese Bodyguard", preco = 3000},
			[8] = {nome = "Reapers Technician", preco = 3000},
			[9] = {nome = "Karl Blaine", preco = 3000},
			[11] = {nome = "Zhang Sun", preco = 3000},
			[12] = {nome = "Reapers Soldier 1", preco = 3000},
			[15] = {nome = "Male Stripper 1", preco = 3000},
			[16] = {nome = "Panau Police", preco = 3000},
			[17] = {nome = "Male Stripper 1", preco = 3000},
			[18] = {nome = "Hacker", preco = 3000},
			[19] = {nome = "Chinese Businessman", preco = 3000},
			[21] = {nome = "Paparazzi", preco = 3000},
			[22] = {nome = "Ular Boys Technician", preco = 3000},
			[23] = {nome = "Scientist", preco = 3000},
			[25] = {nome = "Kane", preco = 3000},
			[26] = {nome = "Boat Captain", preco = 3000},
			[27] = {nome = "Ular Boys Soldier 1", preco = 3000},
			[30] = {nome = "Stranded Copilot", preco = 3000},
			[32] = {nome = "Roaches Technician", preco = 3000},
			[33] = {nome = "Gambler", preco = 3000},
			[34] = {nome = "Tom Sheldon", preco = 3000},
			[36] = {nome = "Politician", preco = 3000},
			[38] = {nome = "Sicini", preco = 3000},
			[39] = {nome = "Thug2", preco = 3000},
			[40] = {nome = "Factory Boss", preco = 3000},
			[42] = {nome = "Black Hand", preco = 3000},
			[44] = {nome = "Ninja", preco = 3000},
			[45] = {nome = "Waiter", preco = 3000},
			[48] = {nome = "Door Man", preco = 3000},
			[49] = {nome = "Government Captain", preco = 3000},
			[51] = {nome = "Rico Rodriguez", preco = 3000},
			[52] = {nome = "Government Soldier 1", preco = 3000},
			[54] = {nome = "Russian Bodyguard", preco = 3000},
			[55] = {nome = "Exclusive Guest Variant 1", preco = 3000},
			[58] = {nome = "Repaers Soldier 2", preco = 3000},
			[59] = {nome = "Roaches Soldier 2", preco = 3000},
			[60] = {nome = "Race Challenge Girl", preco = 3000},
			[61] = {nome = "Generic Soldier", preco = 3000},
			[63] = {nome = "Reapers Elite", preco = 3000},
			[64] = {nome = "Bom Bom Bohilano", preco = 3000},
			[65] = {nome = "Jade Tan", preco = 3000},
			[66] = {nome = "Government Soldier 2", preco = 3000},
			[67] = {nome = "Burned Panay (rocket)", preco = 3000},
			[69] = {nome = "Witness", preco = 3000},
			[70] = {nome = "General Masayo", preco = 3000},
			[71] = {nome = "Saul Sukarno", preco = 3000},
			[74] = {nome = "Baby Panay", preco = 3000},
			[77] = {nome = "Government Elite", preco = 3000},
			[78] = {nome = "Thug Boss", preco = 3000},
			[79] = {nome = "Japanese Veteran", preco = 3000},
			[80] = {nome = "Exclusive Guest", preco = 3000},
			[83] = {nome = "White Tigers", preco = 3000},
			[84] = {nome = "Alexander Mirikov", preco = 3000},
			[85] = {nome = "Roaches Soldier 1", preco = 3000},
			[86] = {nome = "Female Stripper", preco = 3000},
			[87] = {nome = "Ular Boys Elite", preco = 3000},
			[89] = {nome = "Factory Worker", preco = 3000},
			[90] = {nome = "Bolo Santosi", preco = 3000},
			[95] = {nome = "Exclusive Guest Variant 2", preco = 3000},
			[96] = {nome = "Janapese Bodyguard", preco = 3000},
			[97] = {nome = "Burned Panay", preco = 3000},
			[98] = {nome = "Government Pilot", preco = 3000},
			[100] = {nome = "Black Market Dealer", preco = 3000},
			[101] = {nome = "Government Colonel", preco = 3000},
			[103] = {nome = "Ular Boys Soldier 2", preco = 3000},		
		},
		
		[2] = {
			nome = "Chapeus",
			bone = "ragdoll_Head",
			[1] = {nome = "Ushanka", modelo = "pd_arcticvillage_male1.eez/pd_arcticvillage_male-hat.lod", preco = 2000},
			[2] = {nome = "Chapeu do Artico 2", modelo = "pd_arcticvillage_female1.eez/pd_arcticvillage_female-headcloth.lod", preco = 2000},
			[3] = {nome = "Chapeu do Artico 3", modelo = "pd_arcticvillage_female1.eez/pd_arcticvillage_female-headcloth2.lod", preco = 2000},
			[4] = {nome = "Chapeu de Inverno do Artico", modelo = "pd_arcticvillage_female2.eez/pd_arcticvillage_female_2-hat_winter.lod", preco = 2000},
			[5] = {nome = "Chapeu de Inverno do Artico 2", modelo = "pd_arcticvillage_male2.eez/pd_arcticvillage_male_2-hat_winter.lod", preco = 2000},
			[6] = {nome = "Cachecol", modelo = "pd_blackmarket.eez/pd_blackmarket-scarf.lod", preco = 2000},
			[7] = {nome = "Cachecol 2", modelo = "pd_generic_female_3.eez/pd_generic_female_3-hat_scarf.lod", preco = 2000},	
			[8] = {nome = "Xale Masculino", modelo = "pd_desertvillage_female1.eez/pd_desertvillage_female-shawl.lod", preco = 2000},
			[9] = {nome = "Turbante do Deserto", modelo = "pd_desertvillage_male1.eez/pd_desertvillage_male-turban.lod", preco = 2000},
			[10] = {nome = "Chapeu de Pescador", modelo = "pd_fishervillage_male1.eez/pd_fishervillage_male-hat_fisherman.lod", preco = 2000},
			[11] = {nome = "Chapeu de Pescador 2", modelo = "pd_generic_male_1.eez/pd_generic_male_1-hat_fisherman.lod", preco = 2000},	
			[12] = {nome = "Chapeu de Arroz", modelo = "pd_fishervillage_male1.eez/pd_fishervillage_male-ricehat.lod", preco = 2000},
			[13] = {nome = "Chapeu de Arroz 2", modelo = "pd_generic_female.eez/generic_female-ricehat.lod", preco = 2000},
			[14] = {nome = "Chapeu de Arroz 3", modelo = "pd_generic_female_2.eez/pd_generic_female_2-hat_rice.lod", preco = 2000},	
			[15] = {nome = "Chapeu de Arroz 4", modelo = "pd_generic_female_1.eez/pd_generic_female_1-hat_rice.lod", preco = 2000},
			[16] = {nome = "Chapeu de Arroz 5", modelo = "pd_generic_male.eez/pd_generic_male-hat.lod", preco = 2000},	
			[17] = {nome = "Chapeu de Arroz 6", modelo = "pd_generic_male_1.eez/pd_generic_male_1-hat_rice.lod", preco = 2000},	
			[18] = {nome = "Xale Feminino", modelo = "pd_generic_female.eez/generic_female-shawl.lod", preco = 2000},
			[19] = {nome = "Bandana Branca", modelo = "pd_generic_male_2.eez/pd_generic_male_2-hat_linen.lod", preco = 2000},	
			[20] = {nome = "Chapeu de Linho", modelo = "pd_generic_female_1.eez/pd_generic_female_1-hat_linen.lod", preco = 2000},
			[21] = {nome = "Chapeu de Linho 2", modelo = "pd_generic_female_2.eez/pd_generic_female_2-hat_linen.lod", preco = 2000},
			[22] = {nome = "Toalha", modelo = "pd_generic_female_2.eez/pd_generic_female_2-hat_towel.lod", preco = 2000},
			[23] = {nome = "Chapeu de Palha", modelo = "pd_generic_female_3.eez/pd_generic_female_3-hat_straw2.lod", preco = 2000},
			[24] = {nome = "Chapeu de Palha 2", modelo = "pd_generic_female_5.eez/pd_generic_female_5-hat_straw2.lod", preco = 2000},	
			[25] = {nome = "Boina Vermelha", modelo = "pd_gov_base01.eez/pd_gov_base-beret.lod", preco = 2000},
			[26] = {nome = "Bone Militar", modelo = "pd_gov_base01.eez/pd_gov_base-hat.lod", preco = 2000},
			[27] = {nome = "Capacete de Aviador", modelo = "pd_gov_elite.eez/pd_govnewfix_elite-helmet.lod", 3500},
			[28] = {nome = "Bandana de Porteiro", modelo = "pd_ms_doorman.eez/pd_doorman-h_bandana.lod", preco = 2000},
			[29] = {nome = "Chapeu de Japones", modelo = "pd_ms_japaneseveterans.eez/pd_ms_japaneseveterans-hat.lod", preco = 2000},
			[30] = {nome = "Bone de Policia", modelo = "pd_panaupolice.eez/panaupolice-cap.lod", preco = 2000},
			[31] = {nome = "Capacete de Policia", modelo = "pd_panaupolice.eez/panaupolice-helmet.lod", preco = 2000},
			[32] = {nome = "Turbante de Policia", modelo = "pd_panaupolice.eez/panaupolice-turban.lod", preco = 2000},
			[33] = {nome = "Chapeu de Feltro", modelo = "pd_thugs1.eez/pd_thugs-h_felthat.lod", preco = 2000},
			[34] = {nome = "Boina dos Reapers", modelo = "pd_reaperselite1.eez/pd_reapers_elite_male-beret.lod", preco = 2000},
			[35] = {nome = "Bone dos Reapers", modelo = "pd_reaperselite1.eez/pd_reapers_elite_male-cap.lod", preco = 2000},
			[36] = {nome = "Quepi com Peruca", modelo = "pd_tourist_female1.eez/pd_tourist_female-h_keps.lod", preco = 2000},
			[37] = {nome = "Chapeu de Pescador com Peruca", modelo = "pd_tourist_female1.eez/pd_tourist_female-h_fisherhat.lod", preco = 2000},
			[38] = {nome = "Quepi Cinza", modelo = "pd_oilplatform_male1.eez/pd_oilplatform_male-greycap.lod", preco = 2000},
			[39] = {nome = "Chapeu do General", modelo = "pd_ms_civ_strippers_female1.eez/pd_civilian_stripper_female-ht_militarycap.lod", preco = 2000},
			[40] = {nome = "Chapeu Mole", modelo = "pd_ms_civ_strippers_male1.eez/pd_civilian_stripper_male-hat.lod", preco = 2000},
			[41] = {nome = "Chapeu de Cowboy", modelo = "pd_ms_civ_strippers_male2.eez/pd_civilian_stripper_male-cowboyhat.lod", preco = 2000},
			[42] = {nome = "Bandana", modelo = "pd_ms_civ_strippers_male2.eez/pd_civilian_stripper_male-cowboyscarf.lod", preco = 2000},
			[43] = {nome = "Turbante Sujo", modelo = "pd_generic_female_3.eez/pd_generic_female_3-hat_towel.lod", preco = 2000},
			[44] = {nome = "Chapeu Modelado", modelo = "pd_generic_female_5.eez/pd_generic_female_5-hat_cloth.lod", preco = 2000},
			[45] = {nome = "Turbante Preto", modelo = "pd_generic_female_5.eez/pd_generic_female_5-hat_scarf.lod", preco = 2000},
			[46] = {nome = "Bandana Cinza", modelo = "pd_generic_male_3.eez/pd_generic_male_3-hat_linen.lod", preco = 2000},
			[47] = {nome = "Bandana Cinza 2", modelo = "pd_generic_male_1.eez/pd_generic_male_1-hat_linen.lod", preco = 2000},
			[48] = {nome = "Chapeu Estranho", modelo = "pd_generic_male_2.eez/pd_generic_male_2-hat_weird.lod", preco = 2000},
			[49] = {nome = "Fedora", modelo = "pd_generic_male_2.eez/pd_generic_male_2-hat_fedora.lod", preco = 2000},
		},
	}
end